// <auto-generated />
using LostAndFoundAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LostAndFoundAPI.Migrations
{
    [DbContext(typeof(MySqlDbContext))]
    [Migration("20260324221421_AddFoundItems")]
    partial class AddFoundItems
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("LostAndFoundAPI.Domain.Entities.FoundItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ContactEmail")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ContactName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("longtext");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("FoundItems");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Kleidung",
                            Color = "Schwarz",
                            ContactEmail = "max.mustermann@mail.at",
                            ContactName = "Max Mustermann",
                            Description = "Gefunden auf einer Bank beim Bahnhof. Leicht ausgebleicht.",
                            Location = "Bahnhof Dornbirn",
                            Title = "Schwarze Kappe"
                        },
                        new
                        {
                            Id = 2,
                            Category = "Elektronik",
                            Color = "Blau",
                            ContactEmail = "laura.berger@mail.at",
                            ContactName = "Laura Berger",
                            Description = "Lag auf dem Boden nahe dem Haupteingang. Display hat einen kleinen Sprung.",
                            ImageUrl = "https://picsum.photos/seed/iphone/800/600",
                            Location = "FH Vorarlberg",
                            Title = "iPhone 12"
                        },
                        new
                        {
                            Id = 3,
                            Category = "Schlüssel",
                            Color = "Braun",
                            ContactEmail = "thomas.huber@mail.at",
                            ContactName = "Thomas Huber",
                            Description = "Mehrere Schlüssel an einem Ring, brauner Lederanhänger.",
                            ImageUrl = "https://picsum.photos/seed/keys/800/600",
                            Location = "Marktplatz Dornbirn",
                            Title = "Schlüsselbund mit Lederanhänger"
                        },
                        new
                        {
                            Id = 4,
                            Category = "Tasche",
                            Color = "Rot",
                            ContactEmail = "sabrina.koenig@mail.at",
                            ContactName = "Sabrina König",
                            Description = "Gefunden im Bus der Linie 202. Keine sichtbaren Schäden.",
                            ImageUrl = "https://picsum.photos/seed/backpack/800/600",
                            Location = "Stadtbus Dornbirn",
                            Title = "Roter Rucksack"
                        },
                        new
                        {
                            Id = 5,
                            Category = "Schmuck",
                            Color = "Gold",
                            ContactEmail = "daniel.weiss@mail.at",
                            ContactName = "Daniel Weiss",
                            Description = "Lag auf der Toilette im Einkaufszentrum.",
                            ImageUrl = "https://picsum.photos/seed/watch/800/600",
                            Location = "Messepark Dornbirn",
                            Title = "Goldene Armbanduhr"
                        },
                        new
                        {
                            Id = 6,
                            Category = "Kleidung",
                            Color = "Grau",
                            ContactEmail = "julia.fink@mail.at",
                            ContactName = "Julia Fink",
                            Description = "Gefunden beim Sportplatz, Größe M.",
                            ImageUrl = "https://picsum.photos/seed/hoodie/800/600",
                            Location = "Birkenwiese Stadion",
                            Title = "Grauer Hoodie"
                        },
                        new
                        {
                            Id = 7,
                            Category = "Elektronik",
                            Color = "Weiß",
                            ContactEmail = "markus.leitner@mail.at",
                            ContactName = "Markus Leitner",
                            Description = "Ohne Case gefunden, lagen unter einer Sitzbank.",
                            ImageUrl = "https://picsum.photos/seed/airpods/800/600",
                            Location = "Bahnhof Dornbirn",
                            Title = "AirPods Pro"
                        },
                        new
                        {
                            Id = 8,
                            Category = "Kleidung",
                            Color = "Blau",
                            ContactEmail = "anna.mueller@mail.at",
                            ContactName = "Anna Müller",
                            Description = "Ein Paar gestrickte Handschuhe, vermutlich für ein Kind.",
                            ImageUrl = "https://picsum.photos/seed/gloves/800/600",
                            Location = "Stadtgarten Dornbirn",
                            Title = "Kinderhandschuhe"
                        },
                        new
                        {
                            Id = 9,
                            Category = "Accessoire",
                            Color = "Schwarz",
                            ContactEmail = "patrick.meier@mail.at",
                            ContactName = "Patrick Meier",
                            Description = "Leer, keine Ausweise oder Karten enthalten.",
                            ImageUrl = "https://picsum.photos/seed/wallet/800/600",
                            Location = "Innenstadt Dornbirn",
                            Title = "Schwarze Geldbörse"
                        },
                        new
                        {
                            Id = 10,
                            Category = "Tasche",
                            Color = "Dunkelgrau",
                            ContactEmail = "nina.schmid@mail.at",
                            ContactName = "Nina Schmid",
                            Description = "Gepolsterte Tasche, 15 Zoll. Keine Inhalte.",
                            ImageUrl = "https://picsum.photos/seed/laptopbag/800/600",
                            Location = "FH Vorarlberg",
                            Title = "Laptop-Tasche"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
