// <auto-generated />
using System;
using LostAndFoundAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LostAndFoundAPI.Migrations
{
    [DbContext(typeof(MySqlDbContext))]
    [Migration("20260327161718_AddIdentity")]
    partial class AddIdentity
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("LostAndFoundAPI.Domain.Entities.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("longtext");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetime");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("longtext");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("longtext");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("longtext");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("LostAndFoundAPI.Domain.Entities.FoundItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ContactEmail")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ContactName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("longtext");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("FoundItems");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Kleidung",
                            Color = "Schwarz",
                            ContactEmail = "max.mustermann@mail.at",
                            ContactName = "Max Mustermann",
                            Description = "Gefunden auf einer Bank beim Bahnhof. Leicht ausgebleicht.",
                            Location = "Bahnhof Dornbirn",
                            Title = "Schwarze Kappe"
                        },
                        new
                        {
                            Id = 2,
                            Category = "Elektronik",
                            Color = "Blau",
                            ContactEmail = "laura.berger@mail.at",
                            ContactName = "Laura Berger",
                            Description = "Lag auf dem Boden nahe dem Haupteingang. Display hat einen kleinen Sprung.",
                            ImageUrl = "https://picsum.photos/seed/iphone/800/600",
                            Location = "FH Vorarlberg",
                            Title = "iPhone 12"
                        },
                        new
                        {
                            Id = 3,
                            Category = "Schlüssel",
                            Color = "Braun",
                            ContactEmail = "thomas.huber@mail.at",
                            ContactName = "Thomas Huber",
                            Description = "Mehrere Schlüssel an einem Ring, brauner Lederanhänger.",
                            ImageUrl = "https://picsum.photos/seed/keys/800/600",
                            Location = "Marktplatz Dornbirn",
                            Title = "Schlüsselbund mit Lederanhänger"
                        },
                        new
                        {
                            Id = 4,
                            Category = "Tasche",
                            Color = "Rot",
                            ContactEmail = "sabrina.koenig@mail.at",
                            ContactName = "Sabrina König",
                            Description = "Gefunden im Bus der Linie 202. Keine sichtbaren Schäden.",
                            ImageUrl = "https://picsum.photos/seed/backpack/800/600",
                            Location = "Stadtbus Dornbirn",
                            Title = "Roter Rucksack"
                        },
                        new
                        {
                            Id = 5,
                            Category = "Schmuck",
                            Color = "Gold",
                            ContactEmail = "daniel.weiss@mail.at",
                            ContactName = "Daniel Weiss",
                            Description = "Lag auf der Toilette im Einkaufszentrum.",
                            ImageUrl = "https://picsum.photos/seed/watch/800/600",
                            Location = "Messepark Dornbirn",
                            Title = "Goldene Armbanduhr"
                        },
                        new
                        {
                            Id = 6,
                            Category = "Kleidung",
                            Color = "Grau",
                            ContactEmail = "julia.fink@mail.at",
                            ContactName = "Julia Fink",
                            Description = "Gefunden beim Sportplatz, Größe M.",
                            ImageUrl = "https://picsum.photos/seed/hoodie/800/600",
                            Location = "Birkenwiese Stadion",
                            Title = "Grauer Hoodie"
                        },
                        new
                        {
                            Id = 7,
                            Category = "Elektronik",
                            Color = "Weiß",
                            ContactEmail = "markus.leitner@mail.at",
                            ContactName = "Markus Leitner",
                            Description = "Ohne Case gefunden, lagen unter einer Sitzbank.",
                            ImageUrl = "https://picsum.photos/seed/airpods/800/600",
                            Location = "Bahnhof Dornbirn",
                            Title = "AirPods Pro"
                        },
                        new
                        {
                            Id = 8,
                            Category = "Kleidung",
                            Color = "Blau",
                            ContactEmail = "anna.mueller@mail.at",
                            ContactName = "Anna Müller",
                            Description = "Ein Paar gestrickte Handschuhe, vermutlich für ein Kind.",
                            ImageUrl = "https://picsum.photos/seed/gloves/800/600",
                            Location = "Stadtgarten Dornbirn",
                            Title = "Kinderhandschuhe"
                        },
                        new
                        {
                            Id = 9,
                            Category = "Accessoire",
                            Color = "Schwarz",
                            ContactEmail = "patrick.meier@mail.at",
                            ContactName = "Patrick Meier",
                            Description = "Leer, keine Ausweise oder Karten enthalten.",
                            ImageUrl = "https://picsum.photos/seed/wallet/800/600",
                            Location = "Innenstadt Dornbirn",
                            Title = "Schwarze Geldbörse"
                        },
                        new
                        {
                            Id = 10,
                            Category = "Tasche",
                            Color = "Dunkelgrau",
                            ContactEmail = "nina.schmid@mail.at",
                            ContactName = "Nina Schmid",
                            Description = "Gepolsterte Tasche, 15 Zoll. Keine Inhalte.",
                            ImageUrl = "https://picsum.photos/seed/laptopbag/800/600",
                            Location = "FH Vorarlberg",
                            Title = "Laptop-Tasche"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("ClaimType")
                        .HasColumnType("longtext");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("longtext");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("ClaimType")
                        .HasColumnType("longtext");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("longtext");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("longtext");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("RoleId")
                        .HasColumnType("varchar(255)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Name")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Value")
                        .HasColumnType("longtext");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("LostAndFoundAPI.Domain.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("LostAndFoundAPI.Domain.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LostAndFoundAPI.Domain.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("LostAndFoundAPI.Domain.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
